language: node_js
cache:
  directories:
    - node_modules
script:
  - esca-scripts test --serverless && esca-scripts deploy --serverless
notifications:
  email:
    on_success: never
    on_failure: always